<?php

/**
 * PluginsfTimeSpentTimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfTimeSpentTimeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfTimeSpentTimeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfTimeSpentTime');
    }
}