<?php

/**
 * PluginsfTimeSpentProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    timeSpent
 * @subpackage sfTimeSpentProject
 * @author     Stefan Koopmanschap <stefan@stefankoopmanschap.nl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfTimeSpentProject extends BasesfTimeSpentProject
{

}