<?php

/**
 * PluginsfTimeSpentProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfTimeSpentProjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfTimeSpentProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfTimeSpentProject');
    }
}