generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfTimeSpentProject
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_time_spent_project
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:    Projects
        display:  [=name, description]
      filter:  ~
      form:    ~
      edit:
        display:  [name, description]
      new:
        display:  [name, description]